spring:
  profiles:
    active: local



mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar

logging:
  config: classpath:logback-spring.xml
  level:
    com.ibiz.api.controller: INFO
    log4jdbc: INFO

eureka:
  instance:
    instance-id: sales-report-7500
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 7500


--- #local 환경 start

spring:
  profiles: local
  application:
    name: ibiz-sales-report
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver #net.sf.log4jdbc.sql.jdbcapi.DriverSpy # oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.18.120:1521:ibiz #jdbc:log4jdbc:oracle:thin:@192.168.19.230:1521:ibiz # jdbc:oracle:thin:@192.168.19.230:1521:ibiz
    username: IBIZ
    password: IBIZ1229

logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info

--- #local 환경 end

--- #dev 환경 start

spring:
  profiles: dev
  application:
    name: ibiz-sales-report
  redis:
    host: localhost
    port: 6379
    password: dev5791

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver #net.sf.log4jdbc.sql.jdbcapi.DriverSpy # oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.18.120:1521:ibiz #jdbc:log4jdbc:oracle:thin:@192.168.19.230:1521:ibiz # jdbc:oracle:thin:@192.168.19.230:1521:ibiz
    username: IBIZ
    password: IBIZ1229

logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info

  --- #dev 환경 end

--- #staging 환경 start

spring:
  profiles: staging
  application:
    name: ibiz-sales-report
  redis:
    host: localhost
    port: 6379
    password: staging1216


  datasource:
    driver-class-name: oracle.jdbc.OracleDriver #net.sf.log4jdbc.sql.jdbcapi.DriverSpy # oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.18.120:1521:ibiz #jdbc:log4jdbc:oracle:thin:@192.168.19.230:1521:ibiz # jdbc:oracle:thin:@192.168.19.230:1521:ibiz
    username: IBIZ_STAGING
    password: dkdlqlwm#123

logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info

--- #staging 환경 end


--- #prod 환경 start

spring:
  profiles: prod
  application:
    name: ibiz-sales-report
  redis:
    host: localhost
    port: 6379
    password: operation0307

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver #net.sf.log4jdbc.sql.jdbcapi.DriverSpy # oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@183.111.96.41:1521:orcl
    username: IBIZ_PRODUCT
    password: IBIZ1229

logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info

--- #prod 환경 end